workflows:
  android-firebase-distribution:
    name: Android Firebase Distribution
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      java: 17
      vars:
        PACKAGE_NAME: "aero.hyperlog.logbook"
        FIREBASE_APP_ID: "1:988137830414:android:2b3f2642a9a46b388de45f"
        # These are set in Codemagic dashboard:
        # CM_KEYSTORE, CM_KEYSTORE_PATH, CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS, CM_KEY_PASSWORD
        # FIREBASE_SERVICE_ACCOUNT

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'disabled-*'
          include: false
      # Manual trigger only - no auto builds

    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release --dart-define=ENV=prod --build-number=$PROJECT_BUILD_NUMBER

      - name: Generate release notes
        script: |
          VERSION=$(grep 'version:' pubspec.yaml | head -1 | awk '{print $2}' | cut -d'+' -f1)
          echo "v${VERSION} (Build $PROJECT_BUILD_NUMBER)" > release_notes.txt
          echo "" >> release_notes.txt
          echo "Changes:" >> release_notes.txt
          git log -5 --pretty=format:"• %s" >> release_notes.txt

    artifacts:
      - build/**/outputs/**/*.apk

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: $FIREBASE_APP_ID
          groups:
            - alpha-testers
          artifact_type: apk
          release_notes_file: release_notes.txt
