// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyLu_dvAuRyCbxdUshSxJZnzZTes5MKoY',
    appId: '1:988137830414:web:1426f6d90b92323e8de45f',
    messagingSenderId: '988137830414',
    projectId: 'hyperlog-7036c',
    authDomain: 'hyperlog-7036c.firebaseapp.com',
    storageBucket: 'hyperlog-7036c.firebasestorage.app',
    measurementId: 'G-K489FG9XC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKk1PdXH60r_9xNNTEEDsOJdaM33FpLI',
    appId: '1:988137830414:android:2b3f2642a9a46b388de45f',
    messagingSenderId: '988137830414',
    projectId: 'hyperlog-7036c',
    storageBucket: 'hyperlog-7036c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_LtzEVWR6h_M6S12X3Nhek2tEaU_RyLk',
    appId: '1:1021510355637:ios:56570a4073412020bd8cfc',
    messagingSenderId: '1021510355637',
    projectId: 'hyperlog',
    storageBucket: 'hyperlog.firebasestorage.app',
    iosBundleId: 'com.example.hyperlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_LtzEVWR6h_M6S12X3Nhek2tEaU_RyLk',
    appId: '1:1021510355637:ios:56570a4073412020bd8cfc',
    messagingSenderId: '1021510355637',
    projectId: 'hyperlog',
    storageBucket: 'hyperlog.firebasestorage.app',
    iosBundleId: 'com.example.hyperlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV3FkBzflXB0jM_cBNaCd59JpAwMD8RnE',
    appId: '1:1021510355637:web:48e5bcb3988fa855bd8cfc',
    messagingSenderId: '1021510355637',
    projectId: 'hyperlog',
    authDomain: 'hyperlog.firebaseapp.com',
    storageBucket: 'hyperlog.firebasestorage.app',
    measurementId: 'G-L8WQ29B6PR',
  );

}